version: "3.9"

services:
  servergo:
    build: .
    container_name: servergo
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app
    command: ["node", "node/server.js"]

